import 'models/song.dart';

List genres = <String>['Fav', 'Rock', 'Sertanejo', 'Pagode', 'Pop'];

List songs = <Song>[
  Song('Dance Monkey', 'Tones and I'),
  Song('Tudo OK', 'Thiaguinho MT'),
  Song('Não Pare', 'Midian Lima'),
  Song('Anyone', 'Someone You Loved'),
  Song('Girassol', 'Priscilla Alcantara'),
  Song('Você não ama ninguém 2', 'Pineapple'),
  Song('bad guy', 'Billie Eilish'),
  Song('Liberdade Provisória', 'Henrique e Juliano Nardon'),
  Song('Someone You Loved', 'Lewis Capaldi'),
  Song('Tua presença', 'Paulo Neto'),
  Song('Ameno', 'Era'),
];

Map songsObj = {
  'Fav': <Song>[
    Song('Dance Monkey', 'Tones and I'),
    Song('Tudo OK', 'Thiaguinho MT'),
    Song('Não Pare', 'Midian Lima'),
    Song('Anyone', 'Someone You Loved'),
    Song('Girassol', 'Priscilla Alcantara'),
    Song('Você não ama ninguém 2', 'Pineapple'),
    Song('bad guy', 'Billie Eilish'),
    Song('Liberdade Provisória', 'Henrique e Juliano'),
    Song('Someone You Loved', 'Lewis Capaldi'),
    Song('Tua presença', 'Paulo Neto'),
    Song('Ameno', 'Era'),
  ],
  'Rock': <Song>[
    Song('Welcome to the Jungle', 'Guns n\' Roses'),
    Song('Nothing else matters', 'Metallica'),
    Song('Dias atrás', 'CPM 22'),
    Song('Me lambe', 'Raimundos'),
    Song('Rock n Roll', 'Led Zeppelin'),
    Song('Thunderstruck', 'AC/DC'),
    Song('We will rock you', 'Queen'),
    Song('Creep', 'Radiohead'),
    Song('Hey Jude', 'The Beatles'),
    Song('Paint it, Black', 'Rolling Stones'),
  ],
  'Sertanejo': <Song>[
    Song('Liberdade Provisória', 'Henrique & Juliano'),
    Song('Bebi Minha Bicicleta', 'Zé Neto & Cristiano'),
    Song('Fake News', 'Gustavo Miotto'),
    Song('Evidências', 'Chitãozinho & Xororó'),
    Song('É o amor', 'Zezé de Camargo & Luciano'),
    Song('Degrau na Escada', 'Chico Rey & Paraná'),
    Song('Mentira', 'Felipe Araújo'),
    Song('Mil Anos', 'Jorge e Matheus'),
    Song('Barzinho Aleatório', 'Zé Neto & Cristiano'),
    Song('quando a bad bater', 'Luan Santana'),
  ],
  'Pagode': <Song>[
    Song('Bad Liar', 'Imagine Dragons'),
    Song('Dance Monkey', 'Tones and I'),
    Song('Fake Yummy', 'Justin Bieber'),
    Song('Beach House', 'Chainsmokers'),
    Song('Skater Boy', 'Avril Lavigne'),
    Song('Toxic', 'Britney Spears'),
    Song('I want it that way', 'Backstreet Boys'),
    Song('Shallow', 'Lady Gaga'),
    Song('My Hips Dont Lie', 'Shakira'),
    Song('Empire State of Mind', 'Alicia Keys'),
  ],
  'Pop': <Song>[
    Song('Inaraí', 'Kantinguelê'),
    Song('Cilada', 'Molejo'),
    Song('Tanajura', 'Negritude Júnior'),
    Song('Maravilha Te Amar', 'Os Travessos'),
    Song('Maça Do Amor', 'Soweto'),
    Song('Se Melhorar Estraga', 'Karametade'),
    Song('Me Apaixonei Pela Pessoa Errada', 'Exaltasamba'),
    Song('Depois do Prazer', 'Só Pra Contrariar'),
    Song('Cigana', 'Raça Negra'),
    Song('Eterno Amor', 'Sampa Crew'),
  ],
};
